# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: error_codes.proto

require 'google/protobuf'


descriptor_data = "\n\x11\x65rror_codes.proto\x12\x08protocol*\xde\x03\n\tErrorCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x11\n\rUNKNOWN_ERROR\x10\x01\x12\x15\n\x11INVALID_PARAMETER\x10\x02\x12\x12\n\x0eINTERNAL_ERROR\x10\x03\x12\x18\n\x13\x41UTH_TOKEN_REQUIRED\x10\xe8\x07\x12\x17\n\x12\x41UTH_TOKEN_INVALID\x10\xe9\x07\x12\x17\n\x12\x41UTH_TOKEN_EXPIRED\x10\xea\x07\x12\x10\n\x0b\x41UTH_FAILED\x10\xeb\x07\x12\x1f\n\x1a\x41UTH_ALREADY_AUTHENTICATED\x10\xec\x07\x12\x11\n\x0c\x41UTH_TIMEOUT\x10\xed\x07\x12\x16\n\x11\x43ONNECTION_CLOSED\x10\xd0\x0f\x12\x17\n\x12\x43ONNECTION_TIMEOUT\x10\xd1\x0f\x12\x16\n\x11HEARTBEAT_TIMEOUT\x10\xd2\x0f\x12\x1c\n\x17GAME_SERVER_UNAVAILABLE\x10\xb8\x17\x12\x15\n\x10GAME_SERVER_FULL\x10\xb9\x17\x12\x1f\n\x1aGAME_SERVER_CONNECT_FAILED\x10\xba\x17\x12\x1c\n\x17PROTOCOL_INVALID_FORMAT\x10\xa0\x1f\x12\x1a\n\x15PROTOCOL_UNKNOWN_TYPE\x10\xa1\x1f\x12\x1b\n\x16PROTOCOL_DECODE_FAILED\x10\xa2\x1f\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Protocol
  ErrorCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.ErrorCode").enummodule
end
