# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: msg.proto for package 'protocol'

require 'grpc'
require_relative 'msg_pb'

module Protocol
  module GameServerService
    # GatewayとGameServerとの通信サービス
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'protocol.GameServerService'

      # 双方向ストリーミング：一つGateway接続は一つのプレイヤーの接続
      rpc :PlayerSession, stream(::Protocol::G2G_Message), stream(::Protocol::G2G_Message)
    end

    Stub = Service.rpc_stub_class
  end
end
