# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

require 'google/protobuf'


descriptor_data = "\n\tmsg.proto\x12\x08protocol\"0\n\x0bG2G_Message\x12\x13\n\x0bprotocol_id\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x16\n\x07S2C_Key\x12\x0b\n\x03key\x18\x01 \x01(\x03\" \n\x0f\x43\x32S_VerifyToken\x12\r\n\x05token\x18\x01 \x01(\t\"D\n\x0fS2C_VerifyToken\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x03\"\x0f\n\rC2S_Heartbeat2V\n\x11GameServerService\x12\x41\n\rPlayerSession\x12\x15.protocol.G2G_Message\x1a\x15.protocol.G2G_Message(\x01\x30\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Protocol
  G2G_Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.G2G_Message").msgclass
  S2C_Key = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.S2C_Key").msgclass
  C2S_VerifyToken = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.C2S_VerifyToken").msgclass
  S2C_VerifyToken = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.S2C_VerifyToken").msgclass
  C2S_Heartbeat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.C2S_Heartbeat").msgclass
end
